# Generated by Django 4.2.3 on 2023-07-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('gj', models.CharField(max_length=255)),
                ('gs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeightCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StartLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_match', models.BooleanField()),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=25)),
                ('weight', models.IntegerField()),
                ('far_passport', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=255)),
                ('place', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('rank', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('round', models.IntegerField()),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='score.membercats')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.match')),
                ('weight_cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='score.weightcats')),
            ],
        ),
    ]
