# Generated by Django 4.2.3 on 2023-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
