# Generated by Django 4.2.3 on 2023-07-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_match_table_count_alter_startlists_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='arch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='type_match',
            field=models.BooleanField(default=False),
        ),
    ]
