# Generated by Django 4.2.3 on 2023-07-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_match_arch_match_logo_alter_startlists_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_cat', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startlists',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='startlists',
            name='fo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startlists',
            name='sub_rf',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startlists',
            name='trener',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='gj',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='gs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='logo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.membercats'),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='far_passport',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='rank',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='second_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='weight_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.weightcats'),
        ),
        migrations.AddField(
            model_name='startlists',
            name='age_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score.agecats'),
        ),
    ]
