# Generated by Django 4.2.3 on 2023-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_agecats_match_owner_id_startlists_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercats',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='age_cat',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='type_match',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='weight_cat',
        ),
        migrations.AddField(
            model_name='membercats',
            name='age_category',
            field=models.CharField(choices=[('1', 'Мужчины'), ('2', 'Женщины'), ('3', 'Юниоры 19-21'), ('4', 'Юниорки 19-21'), ('5', 'Юниоры 16-18'), ('6', 'Юниорки 16-18'), ('7', 'Юноши 14-15'), ('8', 'Девушки 14-15'), ('9', 'Мастера 40+'), ('10', 'Градн мастера 50+'), ('11', 'Сеньор гранд мастера 60+')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='membercats',
            name='group_category',
            field=models.CharField(choices=[('1', 'Общая'), ('2', 'Любители'), ('3', 'Профессионалы'), ('4', 'Инвалиды'), ('5', 'Инвалиды VIZ'), ('6', 'Инвалиды STAND'), ('7', 'Инвалиты HEAR'), ('8', 'Инвалиды SIT')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='membercats',
            name='type_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membercats',
            name='weight_category',
            field=models.CharField(choices=[('1', '55 КГ'), ('2', '60 КГ'), ('3', '65 КГ'), ('4', '70 КГ'), ('5', '75 КГ'), ('6', '80 КГ'), ('7', '85 КГ'), ('8', '90 КГ'), ('9', '100 КГ'), ('10', '110 КГ'), ('11', '110+ КГ')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='startlists',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AgeCats',
        ),
        migrations.DeleteModel(
            name='WeightCats',
        ),
    ]
