# Generated by Django 4.2.3 on 2023-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_remove_membercats_cat_remove_startlists_age_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercats',
            name='age_category',
            field=models.CharField(choices=[('1', 'Мужчины'), ('2', 'Женщины'), ('3', 'Юниоры 19-21'), ('4', 'Юниорки 19-21'), ('5', 'Юниоры 16-18'), ('6', 'Юниорки 16-18'), ('7', 'Юноши 14-15'), ('8', 'Девушки 14-15'), ('9', 'Мужжины Мастера 40+'), ('10', 'Женщины Мастера 40+'), ('11', 'Мужчины Градн мастера 50+'), ('12', 'Женщины Градн мастера 50+'), ('13', 'Мужчины Сеньор гранд мастера 60+'), ('14', 'Женщины Сеньор гранд мастера 60+')], default='1', max_length=2),
        ),
    ]
