# Generated by Django 4.2.3 on 2023-08-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0014_rename_place_startlists_place_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercats',
            name='table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
