# Generated by Django 4.2.3 on 2023-08-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_membercats_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startlists',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='score.membercats'),
        ),
    ]
