# Generated by Django 4.2.3 on 2023-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_alter_startlists_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='contacts',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
