# Generated by Django 4.2.3 on 2023-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0017_match_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlists',
            name='loses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='startlists',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='membercats',
            name='weight_category',
            field=models.CharField(choices=[('55 КГ', '55 КГ'), ('60 КГ', '60 КГ'), ('65 КГ', '65 КГ'), ('70 КГ', '70 КГ'), ('75 КГ', '75 КГ'), ('80 КГ', '80 КГ'), ('85 КГ', '85 КГ'), ('90 КГ', '90 КГ'), ('100 КГ', '100 КГ'), ('110 КГ', '110 КГ'), ('110+ КГ', '110+ КГ'), ('Абсолютная', 'Абсолютная')], default='55 КГ', max_length=40),
        ),
    ]
