# Generated by Django 4.2.3 on 2023-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0019_alter_startlists_position_alter_startlists_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlists',
            name='pair',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
