# Generated by Django 4.2.3 on 2023-08-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0020_startlists_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercats',
            name='min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
