# Generated by Django 4.2.3 on 2023-08-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0021_membercats_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlists',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
