# Generated by Django 4.2.3 on 2023-08-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0023_alter_startlists_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startlists',
            name='photo',
        ),
    ]
