# Generated by Django 4.2.3 on 2023-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0032_alter_startlists_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startlists',
            name='photo',
            field=models.ImageField(default='static/media/Man.png', upload_to=''),
        ),
    ]
