# Generated by Django 4.2.3 on 2023-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0034_alter_startlists_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
