# Generated by Django 4.2.3 on 2023-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0038_remove_startlists_sub_rf_alter_startlists_fo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
