# Generated by Django 4.2.3 on 2023-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0039_match_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startlists',
            name='far_passport',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='rank',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='team',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='trener',
            field=models.CharField(default='', max_length=255),
        ),
    ]
