# Generated by Django 4.2.3 on 2023-09-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0040_alter_startlists_far_passport_alter_startlists_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercats',
            name='hands',
            field=models.CharField(choices=[('0', 'Обе руки'), ('1', 'Правая'), ('2', 'Левая')], default='1', max_length=1),
        ),
    ]
