# Generated by Django 4.2.3 on 2023-09-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0041_membercats_hands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercats',
            name='hands',
            field=models.CharField(choices=[('1', 'Правая'), ('2', 'Левая')], default='1', max_length=1),
        ),
    ]
