# Generated by Django 4.2.3 on 2023-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0043_remove_match_started_membercats_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startlists',
            name='place_left',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='startlists',
            name='place_right',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
