# Generated by Django 4.2.3 on 2023-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0044_alter_startlists_place_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='current',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
