# Generated by Django 4.2.3 on 2023-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0045_alter_match_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startlists',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
