# Generated by Django 4.2.3 on 2023-09-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0047_members_rename_hands_membercats_hand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='los_name',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='los_second_name',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='los_surname',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='win_name',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='win_second_name',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='win_surname',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='los_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='win_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='match',
            field=models.IntegerField(default=0),
        ),
    ]
