# Generated by Django 4.2.3 on 2023-10-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0049_alter_match_fo_alter_matchhistory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='score.match'),
        ),
    ]
