# Generated by Django 4.2.3 on 2023-12-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0051_alter_matchhistory_category_alter_matchhistory_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercats',
            name='min',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='loses',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='round',
        ),
        migrations.RemoveField(
            model_name='startlists',
            name='win',
        ),
        migrations.AddField(
            model_name='membercats',
            name='final',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='startlists',
            name='act',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startlists',
            name='group',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='startlists',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
