# Generated by Django 4.2.3 on 2023-12-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0052_remove_membercats_min_remove_startlists_loses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='arch',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
