# Generated by Django 4.2.3 on 2023-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0053_remove_match_arch_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlists',
            name='pair',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
