# Generated by Django 4.2.3 on 2024-01-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0054_startlists_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercats',
            name='member_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
