# Generated by Django 4.2.3 on 2024-01-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0055_membercats_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='c56',
            field=models.BooleanField(default=False),
        ),
    ]
