# Generated by Django 4.2.3 on 2024-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0056_match_c56'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('link', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='current',
        ),
    ]
