# Generated by Django 4.2.3 on 2024-02-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0057_armcalendar_remove_match_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArmCalendar',
        ),
    ]
